export const tags = [
    { name: 'ai', description: 'Developing artificial intelligence, machine learning.', isActive: true, postCount: 0, category: 'compsci' },
    { name: 'compsci', description: 'Other computer science/programming', isActive: true, postCount: 0, category: 'compsci' },
    { name: 'distributed', description: 'Distributed systems', isActive: true, postCount: 0, category: 'compsci' },
    { name: 'formalmethods', description: 'Formal methods', isActive: true, postCount: 0, category: 'compsci' },
    { name: 'graphics', description: 'Graphics programming', isActive: true, postCount: 0, category: 'compsci' },
    { name: 'networking', description: 'Networking', isActive: true, postCount: 0, category: 'compsci' },
    { name: 'osdev', description: 'Operating system design and development', isActive: true, postCount: 0, category: 'compsci' },
    { name: 'plt', description: 'Programming language theory, types, design', isActive: true, postCount: 0, category: 'compsci' },
    { name: 'programming', description: 'Use when every tag or no specific tag applies', isActive: true, postCount: 0, category: 'compsci' },
    { name: 'culture', description: 'Technical communities and culture', isActive: true, postCount: 0, category: 'culture' },
    { name: 'law', description: 'Law, patents, and licensing', isActive: true, postCount: 0, category: 'culture' },
    { name: 'person', description: 'Stories about particular persons', isActive: true, postCount: 0, category: 'culture' },
    { name: 'philosophy', description: 'Philosophy', isActive: true, postCount: 0, category: 'culture' },
    { name: 'cogsci', description: 'Cognitive Science', isActive: true, postCount: 0, category: 'field' },
    { name: 'cryptography', description: 'Cryptography', isActive: true, postCount: 0, category: 'field' },
    { name: 'education', description: 'Education', isActive: true, postCount: 0, category: 'field' },
    { name: 'finance', description: 'Finance and economics', isActive: true, postCount: 0, category: 'field' },
    { name: 'hardware', description: 'Hardware', isActive: true, postCount: 0, category: 'field' },
    { name: 'math', description: 'Mathematics', isActive: true, postCount: 0, category: 'field' },
    { name: 'science', description: 'It\'s "Science"', isActive: true, postCount: 0, category: 'field' },
    { name: 'ask', description: 'Ask Lobsters', isActive: true, postCount: 0, category: 'format' },
    { name: 'audio', description: 'Link to audio (podcast, interview)', isActive: true, postCount: 0, category: 'format' },
    { name: 'book', description: 'Link to a book (not an ad or review)', isActive: true, postCount: 0, category: 'format' },
    { name: 'pdf', description: 'Link to a PDF document', isActive: true, postCount: 0, category: 'format' },
    { name: 'show', description: 'Show Lobsters', isActive: true, postCount: 0, category: 'format' },
    { name: 'transcript', description: 'Link to a text transcript', isActive: true, postCount: 0, category: 'format' },
    { name: 'video', description: 'Link to a video', isActive: true, postCount: 0, category: 'format' },
    { name: 'assembly', description: 'Assembly language', isActive: true, postCount: 0, category: 'language' },
    { name: 'c', description: 'C language', isActive: true, postCount: 0, category: 'language' },
    { name: 'c++', description: 'C++ language', isActive: true, postCount: 0, category: 'language' },
    { name: 'csharp', description: 'C# language', isActive: true, postCount: 0, category: 'language' },
    { name: 'clojure', description: 'Clojure language', isActive: true, postCount: 0, category: 'language' },
    { name: 'commonlisp', description: 'Common Lisp language', isActive: true, postCount: 0, category: 'language' },
    { name: 'crystal', description: 'Crystal language', isActive: true, postCount: 0, category: 'language' },
    { name: 'd', description: 'D language', isActive: true, postCount: 0, category: 'language' },
    { name: 'elixir', description: 'Elixir language', isActive: true, postCount: 0, category: 'language' },
    { name: 'elm', description: 'Elm language', isActive: true, postCount: 0, category: 'language' },
    { name: 'erlang', description: 'Erlang language', isActive: true, postCount: 0, category: 'language' },
    { name: 'fsharp', description: 'F# language', isActive: true, postCount: 0, category: 'language' },
    { name: 'go', description: 'Go language', isActive: true, postCount: 0, category: 'language' },
    { name: 'haskell', description: 'Haskell language', isActive: true, postCount: 0, category: 'language' },
    { name: 'java', description: 'Java language', isActive: true, postCount: 0, category: 'language' },
    { name: 'javascript', description: 'JavaScript language', isActive: true, postCount: 0, category: 'language' },
    { name: 'julia', description: 'Julia language', isActive: true, postCount: 0, category: 'language' },
    { name: 'kotlin', description: 'Kotlin language', isActive: true, postCount: 0, category: 'language' },
    { name: 'lua', description: 'Lua language', isActive: true, postCount: 0, category: 'language' },
    { name: 'nim', description: 'Nim language', isActive: true, postCount: 0, category: 'language' },
    { name: 'ocaml', description: 'OCaml language', isActive: true, postCount: 0, category: 'language' },
    { name: 'perl', description: 'Perl language', isActive: true, postCount: 0, category: 'language' },
    { name: 'php', description: 'PHP language', isActive: true, postCount: 0, category: 'language' },
    { name: 'python', description: 'Python language', isActive: true, postCount: 0, category: 'language' },
    { name: 'r', description: 'R language', isActive: true, postCount: 0, category: 'language' },
    { name: 'ruby', description: 'Ruby language', isActive: true, postCount: 0, category: 'language' },
    { name: 'rust', description: 'Rust language', isActive: true, postCount: 0, category: 'language' },
    { name: 'scala', description: 'Scala language', isActive: true, postCount: 0, category: 'language' },
    { name: 'scheme', description: 'Scheme language', isActive: true, postCount: 0, category: 'language' },
    { name: 'swift', description: 'Swift language', isActive: true, postCount: 0, category: 'language' },
    { name: 'typescript', description: 'TypeScript language', isActive: true, postCount: 0, category: 'language' },
    { name: 'zig', description: 'Zig language', isActive: true, postCount: 0, category: 'language' },
    { name: 'art', description: 'Art', isActive: true, postCount: 0, category: 'genre' },
    { name: 'event', description: 'Events, conferences, and meetups', isActive: true, postCount: 0, category: 'genre' },
    { name: 'historical', description: 'History and retrospectives (not for things that happen to be old)', isActive: true, postCount: 0, category: 'genre' },
    { name: 'job', description: 'Employment/Internship opportunities', isActive: true, postCount: 0, category: 'genre' },
    { name: 'news', description: 'General news and current events', isActive: false, postCount: 0, category: 'genre' },
    { name: 'rant', description: 'Rants and raves', isActive: true, postCount: 0, category: 'genre' },
    { name: 'release', description: 'Software releases and announcements', isActive: true, postCount: 0, category: 'genre' },
    { name: 'satire', description: 'Satire, parody, and other humor', isActive: true, postCount: 0, category: 'genre' },
    { name: 'a11y', description: 'accessibility, assistive technology, standards', isActive: true, postCount: 0, category: 'interaction' },
    { name: 'design', description: 'Visual design', isActive: true, postCount: 0, category: 'interaction' },
    { name: 'visualization', description: 'Data visualization', isActive: true, postCount: 0, category: 'interaction' },
    { name: 'android', description: 'Android', isActive: true, postCount: 0, category: 'os' },
    { name: 'dragonflybsd', description: 'DragonFly BSD', isActive: true, postCount: 0, category: 'os' },
    { name: 'freebsd', description: 'FreeBSD', isActive: true, postCount: 0, category: 'os' },
    { name: 'illumos', description: 'illumos', isActive: true, postCount: 0, category: 'os' },
    { name: 'ios', description: 'Apple iOS', isActive: true, postCount: 0, category: 'os' },
    { name: 'linux', description: 'Linux', isActive: true, postCount: 0, category: 'os' },
    { name: 'mac', description: 'Apple macOS', isActive: true, postCount: 0, category: 'os' },
    { name: 'netbsd', description: 'NetBSD', isActive: true, postCount: 0, category: 'os' },
    { name: 'nix', description: 'package manager, distribution, and related systems like guix', isActive: true, postCount: 0, category: 'os' },
    { name: 'openbsd', description: 'OpenBSD', isActive: true, postCount: 0, category: 'os' },
    { name: 'unix', description: '*nix', isActive: true, postCount: 0, category: 'os' },
    { name: 'windows', description: 'Windows', isActive: true, postCount: 0, category: 'os' },
    { name: 'browsers', description: 'Web browsers', isActive: true, postCount: 0, category: 'platforms' },
    { name: 'email', description: 'e-mail', isActive: true, postCount: 0, category: 'platforms' },
    { name: 'games', description: 'Game design and study', isActive: true, postCount: 0, category: 'platforms' },
    { name: 'ipv6', description: 'IPv6', isActive: false, postCount: 0, category: 'platforms' },
    { name: 'merkle-trees', description: 'And related similar data structures. Not business/scam news.', isActive: true, postCount: 0, category: 'platforms' },
    { name: 'mobile', description: 'Mobile app/web development', isActive: true, postCount: 0, category: 'platforms' },
    { name: 'retrocomputing', description: 'Reproductions, emulators, and other revivals of historic technologies', isActive: true, postCount: 0, category: 'platforms' },
    { name: 'wasm', description: 'webassembly', isActive: true, postCount: 0, category: 'platforms' },
    { name: 'web', description: 'Web development and news', isActive: true, postCount: 0, category: 'platforms' },
    { name: 'api', description: 'API development/implementation', isActive: true, postCount: 0, category: 'practices' },
    { name: 'debugging', description: 'Debugging techniques', isActive: true, postCount: 0, category: 'practices' },
    { name: 'devops', description: 'DevOps', isActive: true, postCount: 0, category: 'practices' },
    { name: 'performance', description: 'Performance and optimization', isActive: true, postCount: 0, category: 'practices' },
    { name: 'practices', description: 'Development and team practices', isActive: true, postCount: 0, category: 'practices' },
    { name: 'privacy', description: 'Privacy', isActive: true, postCount: 0, category: 'practices' },
    { name: 'reversing', description: 'Reverse engineering', isActive: true, postCount: 0, category: 'practices' },
    { name: 'scaling', description: 'Scaling and architecture', isActive: true, postCount: 0, category: 'practices' },
    { name: 'security', description: 'Netsec, appsec, and infosec', isActive: true, postCount: 0, category: 'practices' },
    { name: 'testing', description: 'Software testing', isActive: true, postCount: 0, category: 'practices' },
    { name: 'virtualization', description: 'Virtualization', isActive: true, postCount: 0, category: 'practices' },
    { name: 'compilers', description: 'Compiler design', isActive: true, postCount: 0, category: 'tools' },
    { name: 'databases', description: 'Databases (SQL, NoSQL)', isActive: true, postCount: 0, category: 'tools' },
    { name: 'editors', description: 'Code editors and IDEs without a specific tag', isActive: true, postCount: 0, category: 'tools' },
    { name: 'emacs', description: 'Emacs editor', isActive: true, postCount: 0, category: 'tools' },
    { name: 'systemd', description: 'Linux systemd', isActive: true, postCount: 0, category: 'tools' },
    { name: 'vcs', description: 'Git, Mercurial, Perforce, Subversion and other version control systems', isActive: true, postCount: 0, category: 'tools' },
    { name: 'vibecoding', description: 'Using AI/LLM, coding tools. Don\'t also tag with `ai`.', isActive: true, postCount: 0, category: 'tools' },
    { name: 'vim', description: 'Vim editor', isActive: true, postCount: 0, category: 'tools' },
    { name: 'vscode', description: 'Visual Studio Code editor', isActive: true, postCount: 0, category: 'tools' },
];
